#!/usr/bin/env php
<?php

if ($argc == 1) {
    do_self_install();
} else {
    do_error('unknown command \''.$argv[1].'\'');
}
exit(0);

function do_self_install()
{
    if (!is_writable('/usr/sbin/')) {
        do_error('directory /usr/sbin in not writable. Maybe you should run the installation with sudo.');
    }
    copy('https://raw.githubusercontent.com/raulneis/etchosts/master/etchosts', '/usr/sbin/etchosts');

    unlink(__FILE__);

    echo 'etchosts was installed correctly.'.PHP_EOL;
}
