#!/usr/bin/env php
<?php

if ($argc == 1) {
    do_list();
} elseif ($argv[1] == 'help' || $argv[1] == '-h') {
    do_help();

} elseif ($argv[1] == 'add') {
    if ($argc != 4) {
        do_error('etchosts add expects exactly two parameters.'."\n\n".'       etchosts add <host> <ip>'."\n");
    }
    $host = $argv[2];
    $ip = $argv[3];
    if (!validateHost($host)) {
        do_error('Host is not valid.');
    }
    if (!validateIp($ip)) {
        do_error('Ip is not valid.');
    }
    do_add($host, $ip);

} elseif ($argv[1] == 'rm' || $argv[1] == 'remove') {
    if ($argc != 3) {
        do_error('etchosts rm expects exactly one parameter.'."\n\n".'       etchosts [rm|remove] <host>'."\n");
    }
    $host = $argv[2];
    if (!validateHost($host)) {
        do_error('Host is not valid.');
    }
    do_remove($host);

} else {
    do_error('unknown command \''.$argv[1].'\'');

}
exit(0);

function do_help()
{
    echo sprintf("Usage: etchosts -- lists current hosts\n");
    echo sprintf("       etchosts [help|-h] -- shows this help\n");
    echo sprintf("       etchosts add <host> <ip> -- adds the host with the associated ip\n");
    echo sprintf("       etchosts [rm|remove] <host> -- removes the host\n");
}


function do_list()
{
    $data = file_get_contents('/etc/hosts');
    $lines = explode("\n", $data);

    $i = 1;
    foreach ($lines as $line) {
        echo sprintf("\033[37m %02d. \033[0m", $i);
        if (substr($line, 0, 1) != '#') {
            echo sprintf("%s\n", $line);
        } else {
            echo sprintf("\033[37m%s\033[0m\n", $line);
        }
        $i++;
    }
}

function do_error($msg)
{
    echo 'Error: '.$msg."\n";
    exit(1);
}

function do_remove($host)
{
    $regex = regex($host);

    $found = false;
    $new = [];
    foreach (parse() as $data) {
        if ($data['host'] && preg_match($regex, $data['host']) > 0) {
            $found = true;
        } else {
            $new[] = $data;
        }
    }

    if (!$found) {
        do_error('host '.$host.' not found.');
    }

    save($new);
}

function do_add($host, $ip)
{
    $found = false;
    $new = [];
    foreach (parse() as $data) {
        if ($data['host'] && $data['host'] == $host) {
            $found = true;
        } else {
            $new[] = $data;
        }
    }

    if ($found) {
        do_error('host '.$host.' already exists!');
    }

    $sp = str_repeat(' ', (4 * floor((strlen($ip) + 8) / 4)) - strlen($ip));
    $new[] = [
        'ip' => $ip,
        'host' => $host,
        'original' => $ip.$sp.$host,
    ];

    save($new);
}

function parse() {
    $data = file_get_contents('/etc/hosts');
    $lines = explode("\n", $data);

    $ret = [];
    $i = 1;
    foreach ($lines as $line) {
        $original = $line;
        $line = preg_replace('~#.*$~', '', $line);
        $line = trim($line);

        $ip = null;
        $host = null;
        if ($line) {
            list($ip, $host) = preg_split('~\s+~', $line);            
        }

        $ret[] = [
            'line' => $i,
            'ip' => $ip,
            'host' => $host,
            'original' => $original,
        ];

        $i++;
    }

    return $ret;
}

function save($data)
{
    if (!is_writable('/etc/hosts')) {
        do_error('file /etc/hosts is not writable. Maybe you should run etchosts with sudo.');
    }

    $content = [];
    foreach ($data as $d) {
        $content[] = $d['original'];
    }
    $content = implode("\n", $content)."\n";

    print_r($content);

    file_put_contents('/etc/hosts', $content);
}

function regex($host)
{
    $regex = preg_replace('~\.~', '[.]', $host);
    $regex = preg_replace('~\*~', '[^.]*', $regex);
    $regex = '^'.$regex.'$';
    $regex = preg_replace('~#~', '\\#', $regex);
    $regex = '#'.$regex.'#';

    return $regex;
}

function validateIp($ip)
{
    return ! (filter_var($ip, FILTER_VALIDATE_IP) === false);
}

function validateHost($host)
{
    return preg_match('#^([a-zA-Z0-9_-]+)([.]([a-zA-Z0-9_-]+))*[.]?$#', $host) != 0;
}